server:
  port: 8080
  servlet:
    context-path: /demo-stream-kafka
logging:
  level:
    root: INFO
    org.springframework.kafka.listener.KafkaMessageListenerContainer: INFO
spring:
  docker:
    compose:
      skip:
        in-tests: false
      file: "file:@project.basedir@/src/main/resources/compose/docker-compose.yml"
      lifecycle-management: start-and-stop
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: simpleConsumer;completeConsumer
    stream:
      output-bindings: foo-out-0
      bindings:
        simpleConsumer-in-0:
          group: my-group-simple
          destination: input-topic
        completeConsumer-in-0:
          group: my-group-complete
          destination: input-topic
        foo-out-0:
          destination: input-topic

demo:
  jackson:
    mapper:
      enabled: false

management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS

