version: "3"

services:
  kafka:
    image: inditex-docker.jfrog.io/devenv/kafka:7.3.4-r1
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_ADVERTISED_LISTENERS=OUTSIDE://localhost:9092,PLAINTEXT://kafka:29092"
    volumes:
      - "./kafka:/tmp/data"
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    image: inditex-docker.jfrog.io/devenv/zookeeper:7.3.4-r0
    ports:
      - "31510:2181"

  kafka-ui:
    image: provectuslabs/kafka-ui:0.2.1
    ports:
      - "9080:9080"
    environment:
      - "SERVER_PORT=9080"
      - "KAFKA_CLUSTERS_0_NAME=local"
      - "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092"
      - "KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181"
    depends_on:
      kafka:
        condition: service_healthy